# Generated by Django 4.2.27 on 2026-09-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_homebanner_phone_bannner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='phone_bannner',
            field=models.ImageField(blank=True, null=True, upload_to='website/banners/mobile/', verbose_name='تصویر برای موبایل'),
        ),
    ]
