# Generated by Django 4.2.27 on 2026-09-02 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_feature_options_alter_featurevalue_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255, verbose_name='ویژگی')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/size_guides/', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_guides', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'راهنمای سایز',
                'verbose_name_plural': 'راهنمای سایز',
            },
        ),
    ]
