# Generated by Django 4.2.27 on 2026-09-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_sizeguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeguide',
            name='feature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='sizeguide',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مقدار'),
        ),
    ]
