# Generated by Django 4.2.27 on 2026-02-14 23:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponmodel',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کد تخفیف ها'},
        ),
        migrations.AlterModelOptions(
            name='orderitemsmodel',
            options={'verbose_name': 'آیتم سفارش', 'verbose_name_plural': 'آیتم های سفارش'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='useraddressmodel',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز برای استفاده'),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='discount_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='expiration_date',
            field=models.DateTimeField(verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='used_coupons', to=settings.AUTH_USER_MODEL, verbose_name='کاربرانی که کد را استفاده کردند'),
        ),
        migrations.AlterField(
            model_name='orderitemsmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='orderitemsmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.ordermodel', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitemsmodel',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='orderitemsmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='orderitemsmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='orderitemsmodel',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.productvariant', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.useraddressmodel', verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.couponmodel', verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='shipping_method',
            field=models.IntegerField(choices=[(1, 'پست پیشتاز'), (2, 'تیپاکس'), (3, 'ارسال درون اصفهان')], verbose_name='روش ارسال'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار پرداخت'), (2, 'موفقیت آمیز'), (3, 'لغو شده')], default=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='tax_percent',
            field=models.SmallIntegerField(default=10, verbose_name='درصد مالیات'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت نهایی'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='plate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='پلاک'),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='state',
            field=models.CharField(max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='zip_code',
            field=models.CharField(max_length=30, verbose_name='کد پستی'),
        ),
    ]
