# Generated by Django 4.2.27 on 2026-08-19 14:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_feature_options_alter_featurevalue_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_ordermodel_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلاً خانه، محل کار و ...', max_length=100, verbose_name='عنوان آدرس')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='نام گیرنده')),
                ('recipient_phone', models.CharField(max_length=11, verbose_name='شماره تماس گیرنده')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس کامل')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('plaque', models.CharField(blank=True, max_length=20, verbose_name='پلاک')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='واحد')),
                ('is_default', models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
                'ordering': ['-is_default', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=20, verbose_name='نوع تخفیف')),
                ('discount_value', models.PositiveBigIntegerField(help_text='برای درصدی = درصد تخفیف / برای ثابت = مبلغ', validators=[django.core.validators.MinValueValidator(1)], verbose_name='مقدار تخفیف')),
                ('max_discount_amount', models.PositiveBigIntegerField(blank=True, help_text='فقط برای تخفیف درصدی', null=True, verbose_name='حداکثر مبلغ تخفیف')),
                ('minimum_order_amount', models.PositiveBigIntegerField(default=0, verbose_name='حداقل مبلغ سفارش')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ و ساعت شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ و ساعت پایان')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='خالی = بدون محدودیت', null=True, verbose_name='حداکثر تعداد استفاده')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='حداکثر استفاده هر کاربر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.PositiveBigIntegerField(verbose_name='مبلغ تخفیف')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ استفاده')),
            ],
            options={
                'verbose_name': 'استفاده از کد تخفیف',
                'verbose_name_plural': 'استفاده\u200cهای کد تخفیف',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True, verbose_name='شماره سفارش')),
                ('status', models.IntegerField(choices=[(1, 'در انتظار پرداخت'), (2, 'پرداخت شده'), (3, 'در حال پردازش'), (4, 'آماده ارسال'), (5, 'ارسال شده'), (6, 'تحویل داده شده'), (7, 'لغو شده')], default=1, verbose_name='وضعیت سفارش')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='کد تخفیف استفاده شده')),
                ('coupon_discount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ تخفیف کد')),
                ('shipping_title', models.CharField(blank=True, max_length=100, verbose_name='عنوان روش ارسال')),
                ('shipping_cost', models.PositiveBigIntegerField(default=0, verbose_name='هزینه ارسال')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='نام گیرنده')),
                ('recipient_phone', models.CharField(max_length=11, verbose_name='شماره گیرنده')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس کامل')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('plaque', models.CharField(blank=True, max_length=20, verbose_name='پلاک')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='واحد')),
                ('subtotal', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ کالاها')),
                ('discount_amount', models.PositiveBigIntegerField(default=0, verbose_name='مجموع تخفیف')),
                ('total_price', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ نهایی')),
                ('payment_reference', models.CharField(blank=True, max_length=255, verbose_name='شناسه پرداخت')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='کد پیگیری مرسوله')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255, verbose_name='عنوان محصول')),
                ('sku', models.CharField(max_length=50, verbose_name='کد انبار')),
                ('size', models.CharField(max_length=50, verbose_name='سایز')),
                ('color', models.CharField(max_length=100, verbose_name='رنگ')),
                ('color_code', models.CharField(blank=True, max_length=20, verbose_name='کد رنگ')),
                ('original_unit_price', models.PositiveBigIntegerField(verbose_name='قیمت اصلی واحد')),
                ('discount_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف محصول')),
                ('unit_price', models.PositiveBigIntegerField(verbose_name='قیمت نهایی واحد')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('subtotal', models.PositiveBigIntegerField(verbose_name='جمع')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان روش ارسال')),
                ('code', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='کد روش ارسال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('base_cost', models.PositiveBigIntegerField(default=0, verbose_name='هزینه پایه ارسال')),
                ('free_shipping_minimum', models.PositiveBigIntegerField(blank=True, help_text='خالی = ارسال رایگان فعال نیست', null=True, verbose_name='حداقل مبلغ برای ارسال رایگان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='orderitemsmodel',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitemsmodel',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useraddressmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='CouponModel',
        ),
        migrations.DeleteModel(
            name='OrderItemsModel',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
        migrations.DeleteModel(
            name='UserAddressModel',
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['is_active', 'display_order'], name='order_shipp_is_acti_cfac6e_idx'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='سفارش'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.productvariant', verbose_name='تنوع محصول'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.coupon', verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.shippingmethod', verbose_name='روش ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='order.coupon', verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_usage', to='order.order', verbose_name='سفارش'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='اگر خالی باشد، کد تخفیف عمومی است و همه کاربران می\u200cتوانند از آن استفاده کنند.', related_name='available_coupons', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_order_order_i_854de1_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['variant'], name='order_order_variant_e88861_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['sku'], name='order_order_sku_bda0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_date'], name='order_order_user_id_f31fad_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_order_status_2f1723_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='order_order_order_n_fb1851_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['coupon_code'], name='order_order_coupon__560806_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user'], name='order_coupo_coupon__52e4b0_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='order_coupo_code_3ff4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='order_coupo_is_acti_4a6d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'is_default'], name='order_addre_user_id_fc815c_idx'),
        ),
    ]
