# Generated by Django 4.2.27 on 2026-09-06 14:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_address_coupon_couponusage_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponusage',
            options={'ordering': ['-used_date'], 'verbose_name': 'استفاده از کد تخفیف', 'verbose_name_plural': 'استفاده\u200cهای کد تخفیف'},
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='order_addre_user_id_fc815c_idx',
        ),
        migrations.RemoveIndex(
            model_name='coupon',
            name='order_coupo_is_acti_4a6d5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='couponusage',
            name='order_coupo_coupon__52e4b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_order_user_id_f31fad_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_order_order_n_fb1851_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_order_coupon__560806_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='order_order_sku_bda0a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='shippingmethod',
            name='order_shipp_is_acti_cfac6e_idx',
        ),
        migrations.RenameField(
            model_name='couponusage',
            old_name='created_date',
            new_name='used_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='allowed_users',
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_title',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='original_unit_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_global',
            field=models.BooleanField(default=True, help_text='اگر خاموش باشد فقط کاربران انتخاب\u200cشده مجاز هستند.', verbose_name='کد همگانی'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='assigned_coupons', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مالیات'),
        ),
        migrations.AlterField(
            model_name='address',
            name='recipient_phone',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن گیرنده'),
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(help_text='مثلاً خانه، محل کار', max_length=100, verbose_name='عنوان آدرس'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حداکثر مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='خالی = بدون محدودیت', null=True, verbose_name='محدودیت استفاده کل'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit_per_user',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='محدودیت استفاده هر کاربر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.shippingmethod', verbose_name='روش ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.PositiveBigIntegerField(default=0, verbose_name='جمع محصولات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(max_length=50, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_title',
            field=models.CharField(max_length=200, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.PositiveBigIntegerField(default=0, verbose_name='جمع'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='base_cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینه ارسال'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='code',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='free_shipping_minimum',
            field=models.PositiveBigIntegerField(blank=True, help_text='خالی = ارسال رایگان خودکار وجود ندارد', null=True, verbose_name='حداقل مبلغ ارسال رایگان'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user'], name='order_addre_user_id_64d568_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['is_default'], name='order_addre_is_defa_84957d_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active'], name='order_coupo_is_acti_ff38f5_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['start_date', 'end_date'], name='order_coupo_start_d_70227f_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon'], name='order_coupo_coupon__2bef4c_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['user'], name='order_coupo_user_id_ae065c_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['used_date'], name='order_coupo_used_da_515d87_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='order_order_user_id_a7f1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_date'], name='order_order_created_978638_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_code'], name='order_order_trackin_034704_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['is_active'], name='order_shipp_is_acti_85ca22_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['display_order'], name='order_shipp_display_922f15_idx'),
        ),
    ]
