# Generated by Django 4.2.27 on 2026-09-06 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_alter_couponusage_options_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ پرداخت')),
                ('currency', models.CharField(default='IRR', max_length=10, verbose_name='واحد پول')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین پال')], default='zarinpal', max_length=50, verbose_name='درگاه پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'موفق'), ('failed', 'ناموفق'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('authority', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='شناسه Authority')),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره مرجع تراکنش')),
                ('gateway_data', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات درگاه')),
                ('error_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد خطای درگاه')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطای درگاه')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='order.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداختها',
                'ordering': ['-created_date'],
            },
        ),
        migrations.DeleteModel(
            name='PaymentModel',
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payment_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payment_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway', 'status'], name='payment_gateway_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_date'], name='payment_created_idx'),
        ),
    ]
