# Generated by Django 4.2.27 on 2026-08-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_date'], 'verbose_name': 'نظرات محصولات', 'verbose_name_plural': 'نظرات محصولات'},
        ),
    ]
